version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db_tstoddd
    ports:
      - "3326:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_tstoddd
    volumes:
      - db_ts_to_ddd:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_ts_to_ddd: